### ISSUE TITLE
BUG: internal error when a combo order is received

### ISSUE THREAD

**Issue by fantabolous** [blampe/IbPy#10]
I've been using ibpy for about half a year now and it's worked wonderfully. However I'm now trying to use reqAllOpenOrders, and when a combo order (e.g. an order with 2 or more legs, such as a futures spread) gets sent back, it gives me this msg, after which point the connection is lost (I think):
<error id=None, errorCode=None, errorMsg=__init__() takes exactly 1 argument (9 given)>

I'm using ib-api 0.9.70 from https://pypi.python.org/pypi/ib-api, and the latest version of TWS (e.g. I run it from the website).

**Comment by valiant-falstaff** [comment]
Fix at https://github.com/blampe/IbPy/pull/11
