### ISSUE TITLE
reqAccountUpdates for linked accounts

### ISSUE THREAD

**Issue by jonathanng** [blampe/IbPy#12]
Anyone else having issues grabbing account updates simultaneously from multiple accounts?

**Comment by paco88** [comment]
I have same issue here.  I have 2 accounts and if I do this in API

reqAccountUpdates(true, "U000001");
reqAccountUpdates(true, "U000002");

I only receive updates from U000002, as if the first request had been unsubscribed.

Any help would be appreciated.

**Comment by DMTSource** [comment]
I just tested the issue and agree with @paco88 about the issue. Just to be clear I have two linked accounts so in TWS I can easily switch between my accounts without any different login required.

I attempted to perform the same test above, then I though what if we could use two separate clients to attempt to subscribe, but that also fails with error:
<error id=-1, errorCode=2101, errorMsg=Unable subscribe to account as the following clients are subscribed to a different account.{0}>

I also then went and read on the 'ibpy discuss' group on google groups and found that there is a 3 min window between account updates when the task is not "forced". I thought maybe its only throwing an account update for 1 account every few minutes... but sleeping for a long time while allowing messages to stream still shows the same results in the end.
https://groups.google.com/forum/#!searchin/ibpy-discuss/reqAccountUpdates/ibpy-discuss/y99T0VbbC7A/BApMJmEjHv8J

My Test Code:

```
from ib.opt import ibConnection, message
from time import sleep


""" SAMPLE OUTPUT WITH VALID ACCOUNT STRINGS

Server Version: 76
TWS Time at connection:20160506 12:14:44 EST
Second account downloaded 4 messages.


Server Version: 76
TWS Time at connection:20160506 12:14:45 EST
Server Version: 76
TWS Time at connection:20160506 12:14:45 EST
<error id=-1, errorCode=2101, errorMsg=Unable subscribe to account as the following clients are subscribed to a different account.{1}>
First account downloaded 4 messages.

"""

test_dict = {}

def error(msg):
	if msg.errorCode != 2104 and msg.errorCode != 2106:
		print msg

def account_time(msg):
	print msg

def account_value(msg):
	test_dict[msg.accountName] = msg

if __name__ == '__main__':

	# YOU NEED TO ADD YOUR ACCOUNT NUMBERS HERE FOR THIS TO WORK
	account_1 = ""
	account_2 = ""

	con = ibConnection(port = 7496, clientId = 0)
	con.register(error, message.error)
	con.register(account_value, message.updateAccountValue)
	#con.register(account_time, message.updateAccountTime)
	con.connect()

	sleep(0.1)

	con.reqAccountUpdates(True, account_1)
	con.reqAccountUpdates(True, account_2)

	sleep(1.0)

	if account_1 in test_dict:
		print 'First account downloaded %d messages.'%len(test_dict[account_1])
	if account_2 in test_dict:
		print 'Second account downloaded %d messages.'%len(test_dict[account_2])

	con.reqAccountUpdates(False, account_1)
	con.reqAccountUpdates(False, account_2)
	con.disconnect()


	sleep(1.0)
	print '\n'


	# That didnt work, we will have to use two separate clients(remember we only get 8 per TWS I believe)
	test_dict = {}

	con1 = ibConnection(port = 7496, clientId = 1)
	con1.register(error, message.error)
	con1.register(account_value, message.updateAccountValue)
	con1.connect()
	sleep(0.1)
	con1.reqAccountUpdates(True, account_1)

	con2 = ibConnection(port = 7496, clientId = 2)
	con2.register(error, message.error)
	con2.register(account_value, message.updateAccountValue)
	con2.connect()
	sleep(0.1)
	con2.reqAccountUpdates(True, account_2)

	sleep(1.0)

	if account_1 in test_dict:
		print 'First account downloaded %d messages.'%len(test_dict[account_1])
	if account_2 in test_dict:
		print 'Second account downloaded %d messages.'%len(test_dict[account_2])

	con1.reqAccountUpdates(False, account_1)
	con1.disconnect()
	con2.reqAccountUpdates(False, account_2)
	con2.disconnect()
```

**Comment by paco88** [comment]
Thanks @DMTSource for a good workaround.

BTW, I found in the IB C# API guide that reqAccountUpdates() can only work on single account: "You can subscribe to only one account at a time. ... Consider using reqPositions() if you want to retrieve all your accounts' portfolios directly."

https://www.interactivebrokers.co.uk/en/software/api/apiguide/csharp/reqaccountupdates.htm

I wonder why it is not in the Java API guide.

**Comment by fzumstein** [comment]
Seems resolved, please reopen if you disagree.
