### ISSUE TITLE
commissionReport.

### ISSUE THREAD

**Issue by spinor8** [blampe/IbPy#26]
Is anyone having issues with getting the commissions back from the commissionReport?

I printed out the message output from the commissionReport and the fill event that preceded it.
**orderStatus orderId=20, status=Filled, filled=2, remaining=0, avgFillPrice=2060.5, permId=1594773782, parentId=0, lastFillPrice=2060.5, clientId=11, whyHeld=None
commissionReport commissionReport= ib.ext.CommissionReport.CommissionReport object at 0x110b8afd0**

As you can see the attributes are displayed correctly for OrderStatus (and many other message types) but not for commissionReport.

Helpful hints or suggestions for a workaround are much appreciated. Thanks.

**Comment by anthonyng2** [comment]
You need to unpack further. The commission report has attributed such as 
- dot  m_commission
- dot m_currency
and more.

**Comment by spinor8** [comment]
Thanks Anthony.
