### ISSUE TITLE
Please update the article about "Getting Started with IbPy" from google to github. 

### ISSUE THREAD

**Issue by ccnxabc** [blampe/IbPy#27]
Hello everyone
Here is mainland China.All the url below is blocked by Great FireWall and I CAN NOT get any information about "Getting Started with IbPy" .

Please update the article about "Getting Started with IbPy" from google to github. 

Thanks a lot

"
How do I use IbPy?
See the IbPy wiki page "Getting Started with IbPy":
http://code.google.com/p/ibpy/wiki/GettingStarted
"

**Comment by 4ever911** [comment]
Go get yourself a VPN

**Comment by ofertal** [comment]
Do you still need assistance?

**Comment by fzumstein** [comment]
The article is pretty much outdated, but for the fun of it, I've added a screenshot. However, it makes more sense to look at the new wiki here on GitHub.

![screen shot 2016-10-19 at 15 22 51](https://cloud.githubusercontent.com/assets/2265504/19520316/1edcf1fc-9610-11e6-957a-5f9dcacf2601.png)
