### ISSUE TITLE
is there a way to get commissions?

### ISSUE THREAD

**Issue by expectedvalue073** [blampe/IbPy#35]
The IB API includes in reqExecutions a way to get the commissions (fees) for each trade, but I don't see it being returned.

**Comment by expectedvalue073** [comment]
Looking at the source, there is support for CommissionReport, but unlike reqExecutions I don't see a way to request commissions. My goal is to get fees paid for executed trades.

**Comment by DMTSource** [comment]
From the docs(I suggest these over the ibpy source as ibpy is generated
from the java api), you should be able to register *commissionReport* and
then it will be called either automatically after a trade execution or when
*reqExecutions* is used.

Source:
https://www.interactivebrokers.com/en/software/api/apiguide/java/reqexecutions.htm
https://www.interactivebrokers.com/en/software/api/apiguide/java/commissionreport_event.htm


On Thu, Nov 24, 2016 at 11:07 AM, expectedvalue073 <notifications@github.com

**Comment by expectedvalue073** [comment]
I have reqExecutions and I added message.commissionReport as a callback, but I simply do not get calls on the callback intended for commissions.

**Comment by expectedvalue073** [comment]
To add, I have a callback registered for "ExecDetails" and that one works fine. I can get a list of all executed trades. But the commission callback does not get called.

**Comment by expectedvalue073** [comment]
I wrote a print statement on line 35 of opt/dispatcher.py and here is what I got:
```

Server Version: 76
TWS Time at connection:20161124 14:08:10 EST
managedAccounts {'accountsList': 'xxxxxxxxxxxx'}
nextValidId {'orderId': 1}
error {'errorCode': 2104, 'errorMsg': 'Market data farm connection is OK:usfarm.us', 'id': -1}
error {'errorCode': 2104, 'errorMsg': 'Market data farm connection is OK:usfarm', 'id': -1}
error {'errorCode': 2106, 'errorMsg': 'HMDS data farm connection is OK:ushmds', 'id': -1}
execDetails {'reqId': 1, 'execution': <ib.ext.Execution.Execution object at 0x000000000346D5C0>, 'contract': <ib.ext.Contract.Contract object at 0x000000000347EB00>}
execDetails {'reqId': 1, 'execution': <ib.ext.Execution.Execution object at 0x000000000347EAC8>, 'contract': <ib.ext.Contract.Contract object at 0x000000000347EB00>}
execDetails {'reqId': 1, 'execution': <ib.ext.Execution.Execution object at 0x000000000347EB00>, 'contract': <ib.ext.Contract.Contract object at 0x000000000347EAC8>}
...
execDetails {'reqId': 1, 'execution': <ib.ext.Execution.Execution object at 0x000000000347EB00>, 'contract': <ib.ext.Contract.Contract object at 0x000000000347EAC8>}
execDetailsEnd {'reqId': 1}
```
I don't see anything regarding commissions, and I have commissions registered.

**Comment by expectedvalue073** [comment]
I added another print in line 122 of ext/EReader.py

```
print msgId
```

and I do not see a 59 (COMMISSION_REPORT), but a lot of 11's (EXECUTION_DATA).

**Comment by DMTSource** [comment]
Could this be related to your issue with phone app executions RE orderIDs? If so, you could try changing your ibpy script to use the master client id when connecting. This is used to monitor executions across a wider scope but  for other api clients on the network and for TWS itself I believe.

Source (the section re Master API client ID):
https://www.interactivebrokers.com/en/software/tws/usersguidebook/configuretws/apisettings.htm

**Comment by expectedvalue073** [comment]
You are right. The Master API client ID solved it.
